services:
  database:
    image: 'postgres:17.2'
    ports: 
      - '15432:5432'
    environment:
      POSTGRES_USER: backend
      POSTGRES_DB: klatre
      POSTGRES_PASSWORD: 123qwe

  redis:
    image: 'redis:7-alpine'
    ports:
      - '6379:6379'